import '../models/models.dart';

class StubDataService {
  // Singleton pattern
  static final StubDataService _instance = StubDataService._internal();
  factory StubDataService() => _instance;
  StubDataService._internal();

  // Character data
  List<Character> get sampleCharacters => [
    Character(
      id: 'char_1',
      userId: 'user_1',
      name: 'Naruto Uzumaki',
      village: 'Konoha',
      clanId: 'clan_uzumaki',
      clanRank: 'member',
      ninjaRank: 'Genin',
      elements: ['wind'],
      bloodline: null,
      strength: 15000,
      intelligence: 8000,
      speed: 18000,
      defense: 12000,
      willpower: 20000,
      bukijutsu: 25000,
      ninjutsu: 30000,
      taijutsu: 28000,
      genjutsu: 0,
      jutsuMastery: {'rasengan': 5, 'shadow_clone': 8},
      currentHp: 150000,
      currentChakra: 80000,
      currentStamina: 180000,
      experience: 45000,
      level: 12,
      hpRegenRate: 100,
      cpRegenRate: 100,
      spRegenRate: 100,
      ryoOnHand: 5000,
      ryoBanked: 15000,
      villageLoyalty: 85,
      outlawInfamy: 0,
      marriedTo: null,
      senseiId: 'char_kakashi',
      studentIds: [],
      pvpWins: 15,
      pvpLosses: 8,
      pveWins: 45,
      pveLosses: 3,
      medicalExp: 0,
      avatarUrl: 'assets/avatars/naruto.png',
      gender: 'male',
      inventory: [],
      equippedItems: {},
    ),
    Character(
      id: 'char_2',
      userId: 'user_2',
      name: 'Sasuke Uchiha',
      village: 'Konoha',
      clanId: 'clan_uchiha',
      clanRank: 'member',
      ninjaRank: 'Genin',
      elements: ['fire', 'lightning'],
      bloodline: 'Sharingan',
      strength: 16000,
      intelligence: 12000,
      speed: 20000,
      defense: 10000,
      willpower: 15000,
      bukijutsu: 32000,
      ninjutsu: 35000,
      taijutsu: 30000,
      genjutsu: 15000,
      jutsuMastery: {'chidori': 6, 'fireball': 7, 'sharingan': 3},
      currentHp: 160000,
      currentChakra: 120000,
      currentStamina: 200000,
      experience: 52000,
      level: 13,
      hpRegenRate: 100,
      cpRegenRate: 100,
      spRegenRate: 100,
      ryoOnHand: 8000,
      ryoBanked: 25000,
      villageLoyalty: 70,
      outlawInfamy: 5,
      marriedTo: null,
      senseiId: 'char_kakashi',
      studentIds: [],
      pvpWins: 22,
      pvpLosses: 5,
      pveWins: 52,
      pveLosses: 2,
      medicalExp: 0,
      avatarUrl: 'assets/avatars/sasuke.png',
      gender: 'male',
      inventory: [],
      equippedItems: {},
    ),
  ];

  // Mission data
  List<Mission> get sampleMissions => [
    Mission(
      id: 'mission_1',
      title: 'Escort the Merchant',
      description: 'Protect a merchant traveling from Konoha to the next village. Bandits have been spotted in the area.',
      rank: MissionRank.D,
      type: MissionType.mission,
      village: 'Konoha',
      requiredLevel: 5,
      requiredRank: 1, // Genin
      experienceReward: 500,
      ryoReward: 1000,
      itemRewards: ['basic_scroll'],
      jutsuRewards: [],
      statRequirements: {'speed': 5000},
      requiredElements: [],
      requiredBloodline: null,
      estimatedDuration: 30,
      isRepeatable: true,
      isActive: true,
      expiryDate: null,
      isDarkOps: false,
      isStoryline: false,
      prerequisiteMissionId: null,
      tags: ['escort', 'combat'],
    ),
    Mission(
      id: 'mission_2',
      title: 'Investigate Missing Ninja',
      description: 'A Chunin has gone missing while on patrol. Investigate the area and report back.',
      rank: MissionRank.C,
      type: MissionType.mission,
      village: 'Konoha',
      requiredLevel: 15,
      requiredRank: 2, // Chunin
      experienceReward: 1500,
      ryoReward: 3000,
      itemRewards: ['chunin_scroll', 'medical_supplies'],
      jutsuRewards: [],
      statRequirements: {'intelligence': 8000, 'speed': 12000},
      requiredElements: [],
      requiredBloodline: null,
      estimatedDuration: 60,
      isRepeatable: false,
      isActive: true,
      expiryDate: null,
      isDarkOps: false,
      isStoryline: true,
      prerequisiteMissionId: 'mission_1',
      tags: ['investigation', 'storyline'],
    ),
    Mission(
      id: 'mission_3',
      title: 'Dark Ops: Infiltrate Enemy Base',
      description: 'Secret mission to infiltrate an enemy base and gather intelligence. Maximum secrecy required.',
      rank: MissionRank.A,
      type: MissionType.darkOps,
      village: 'Konoha',
      requiredLevel: 30,
      requiredRank: 2, // Chunin+
      experienceReward: 5000,
      ryoReward: 8000,
      itemRewards: ['elite_scroll', 'stealth_gear'],
      jutsuRewards: ['shadow_step'],
      statRequirements: {'speed': 20000, 'intelligence': 15000, 'ninjutsu': 25000},
      requiredElements: [],
      requiredBloodline: null,
      estimatedDuration: 120,
      isRepeatable: false,
      isActive: true,
      expiryDate: null,
      isDarkOps: true,
      isStoryline: false,
      prerequisiteMissionId: null,
      tags: ['stealth', 'intelligence', 'dark_ops'],
    ),
  ];

  // Clan data
  List<Clan> get sampleClans => [
    Clan(
      id: 'clan_uzumaki',
      name: 'Uzumaki Clan',
      description: 'Ancient clan known for their sealing techniques and spiral patterns. Masters of fuinjutsu.',
      village: 'Konoha',
      leaderId: 'char_uzumaki_leader',
      advisorIds: ['char_uzumaki_advisor_1', 'char_uzumaki_advisor_2'],
      memberIds: ['char_1', 'char_uzumaki_member_1'],
      createdAt: DateTime(2020, 1, 1),
      isActive: true,
      statBonuses: {'chakra': 0.15, 'willpower': 0.10},
      specialAbilities: ['Fuinjutsu Mastery', 'Chakra Sensing'],
      maxMembers: 20,
      isPublic: true,
      isDarkOps: false,
      requirements: 'Must demonstrate sealing aptitude',
      applicationFee: 1000,
    ),
    Clan(
      id: 'clan_uchiha',
      name: 'Uchiha Clan',
      description: 'Prestigious clan with the Sharingan bloodline. Masters of fire techniques and genjutsu.',
      village: 'Konoha',
      leaderId: 'char_uchiha_leader',
      advisorIds: ['char_uchiha_advisor_1'],
      memberIds: ['char_2', 'char_uchiha_member_1'],
      createdAt: DateTime(2020, 1, 1),
      isActive: true,
      statBonuses: {'ninjutsu': 0.20, 'intelligence': 0.15},
      specialAbilities: ['Sharingan', 'Fire Affinity', 'Genjutsu Resistance'],
      maxMembers: 25,
      isPublic: false,
      isDarkOps: false,
      requirements: 'Must possess Uchiha bloodline',
      applicationFee: 5000,
    ),
  ];

  // Jutsu data
  List<Jutsu> get sampleJutsus => [
    Jutsu(
      id: 'rasengan',
      name: 'Rasengan',
      description: 'A powerful sphere of rotating chakra that causes massive damage on impact.',
      type: JutsuType.ninjutsu,
      element: JutsuElement.neutral,
      bloodline: null,
      chakraCost: 500,
      staminaCost: 200,
      cooldownTurns: 3,
      range: 2,
      basePower: 800,
      statScaling: {'chakra': 0.5, 'intelligence': 0.3},
      effects: ['high_damage', 'piercing'],
      maxMasteryLevel: 10,
      masteryBonuses: {1: 0, 2: 50, 3: 100, 4: 150, 5: 200, 6: 250, 7: 300, 8: 350, 9: 400, 10: 500},
      requiredLevel: 10,
      statRequirements: {'chakra': 10000, 'intelligence': 8000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/jutsus/rasengan.png',
      tags: ['ninjutsu', 'high_power', 'signature'],
      isActive: true,
    ),
    Jutsu(
      id: 'chidori',
      name: 'Chidori',
      description: 'A lightning technique that concentrates chakra into the hand, creating a powerful piercing attack.',
      type: JutsuType.ninjutsu,
      element: JutsuElement.lightning,
      bloodline: null,
      chakraCost: 600,
      staminaCost: 300,
      cooldownTurns: 4,
      range: 1,
      basePower: 900,
      statScaling: {'chakra': 0.6, 'speed': 0.4},
      effects: ['high_damage', 'lightning', 'piercing'],
      maxMasteryLevel: 10,
      masteryBonuses: {1: 0, 2: 60, 3: 120, 4: 180, 5: 240, 6: 300, 7: 360, 8: 420, 9: 480, 10: 540},
      requiredLevel: 12,
      statRequirements: {'chakra': 12000, 'speed': 15000},
      requiredElements: ['lightning'],
      requiredBloodline: null,
      iconPath: 'assets/jutsus/chidori.png',
      tags: ['ninjutsu', 'lightning', 'high_power'],
      isActive: true,
    ),
    Jutsu(
      id: 'sharingan',
      name: 'Sharingan',
      description: 'The legendary dojutsu of the Uchiha clan. Provides enhanced perception and genjutsu abilities.',
      type: JutsuType.bloodline,
      element: JutsuElement.neutral,
      bloodline: 'Sharingan',
      chakraCost: 100,
      staminaCost: 50,
      cooldownTurns: 0,
      range: 0,
      basePower: 0,
      statScaling: {},
      effects: ['enhanced_perception', 'genjutsu_boost', 'copy_techniques'],
      maxMasteryLevel: 15,
      masteryBonuses: {1: 0, 2: 100, 3: 200, 4: 300, 5: 400, 6: 500, 7: 600, 8: 700, 9: 800, 10: 900, 11: 1000, 12: 1100, 13: 1200, 14: 1300, 15: 1500},
      requiredLevel: 8,
              statRequirements: {'genjutsu': 5000},
      requiredElements: [],
      requiredBloodline: 'Sharingan',
      iconPath: 'assets/jutsus/sharingan.png',
      tags: ['bloodline', 'dojutsu', 'perception'],
      isActive: true,
    ),
  ];

  // Item data
  List<Item> get sampleItems => [
    // WEAPONS
    Item(
      id: 'item_1',
      name: 'Kunai',
      description: 'A standard throwing knife used by ninja. Basic but reliable weapon.',
      type: ItemType.weapon,
      equipmentSlot: EquipmentSlot.weapon,
      statBonuses: {'strength': 100, 'speed': 50},
      statMultipliers: {},
      specialEffects: ['throwing_weapon'],
      durability: 100,
      maxDurability: 100,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 100,
      sellPrice: 50,
      shopCategory: 'weapons',
      isAvailableInShop: true,
      requiredLevel: 1,
      statRequirements: {},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/kunai.png',
      tags: ['weapon', 'throwing', 'basic'],
      isActive: true,
      rarity: 'Common',
    ),
    Item(
      id: 'item_2',
      name: 'Shuriken',
      description: 'A four-pointed throwing star. Excellent for ranged combat.',
      type: ItemType.weapon,
      equipmentSlot: EquipmentSlot.weapon,
      statBonuses: {'speed': 150, 'bukijutsu': 100},
      statMultipliers: {},
      specialEffects: ['throwing_weapon', 'multi_hit'],
      durability: 80,
      maxDurability: 80,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 200,
      sellPrice: 100,
      shopCategory: 'weapons',
      isAvailableInShop: true,
      requiredLevel: 3,
      statRequirements: {'speed': 2000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/shuriken.png',
      tags: ['weapon', 'throwing', 'ranged'],
      isActive: true,
      rarity: 'Common',
    ),
    Item(
      id: 'item_3',
      name: 'Chakra Blade',
      description: 'A sword that channels chakra for enhanced cutting power.',
      type: ItemType.weapon,
      equipmentSlot: EquipmentSlot.weapon,
      statBonuses: {'strength': 300, 'bukijutsu': 200, 'ninjutsu': 100},
      statMultipliers: {'strength': 1.1},
      specialEffects: ['chakra_enhanced', 'elemental_boost'],
      durability: 150,
      maxDurability: 150,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 1500,
      sellPrice: 750,
      shopCategory: 'weapons',
      isAvailableInShop: true,
      requiredLevel: 8,
      statRequirements: {'strength': 5000, 'ninjutsu': 3000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/chakra_blade.png',
      tags: ['weapon', 'sword', 'chakra'],
      isActive: true,
      rarity: 'Uncommon',
    ),
    Item(
      id: 'item_4',
      name: 'Lightning Katana',
      description: 'A katana imbued with lightning chakra. Extremely fast and deadly.',
      type: ItemType.weapon,
      equipmentSlot: EquipmentSlot.weapon,
      statBonuses: {'speed': 400, 'strength': 250, 'bukijutsu': 300},
      statMultipliers: {'speed': 1.2},
      specialEffects: ['lightning_enhanced', 'chain_lightning', 'paralyze'],
      durability: 200,
      maxDurability: 200,
      isRepairable: true,
      isTradeable: true,
      isDroppable: false,
      buyPrice: 5000,
      sellPrice: 2500,
      shopCategory: 'weapons',
      isAvailableInShop: true,
      requiredLevel: 15,
      statRequirements: {'speed': 12000, 'strength': 8000},
      requiredElements: ['lightning'],
      requiredBloodline: null,
      iconPath: 'assets/items/lightning_katana.png',
      tags: ['weapon', 'katana', 'lightning'],
      isActive: true,
      rarity: 'Rare',
    ),
    Item(
      id: 'item_5',
      name: 'Flame Scythe',
      description: 'A massive scythe wreathed in flames. Devastating in close combat.',
      type: ItemType.weapon,
      equipmentSlot: EquipmentSlot.weapon,
      statBonuses: {'strength': 600, 'willpower': 200, 'bukijutsu': 400},
      statMultipliers: {'strength': 1.3},
      specialEffects: ['fire_enhanced', 'burning', 'area_damage'],
      durability: 250,
      maxDurability: 250,
      isRepairable: true,
      isTradeable: false,
      isDroppable: false,
      buyPrice: 12000,
      sellPrice: 6000,
      shopCategory: 'weapons',
      isAvailableInShop: true,
      requiredLevel: 25,
      statRequirements: {'strength': 20000, 'willpower': 10000},
      requiredElements: ['fire'],
      requiredBloodline: null,
      iconPath: 'assets/items/flame_scythe.png',
      tags: ['weapon', 'scythe', 'fire'],
      isActive: true,
      rarity: 'Epic',
    ),
    Item(
      id: 'item_6',
      name: 'Thunder Hammer',
      description: 'A legendary hammer that calls down lightning from the heavens.',
      type: ItemType.weapon,
      equipmentSlot: EquipmentSlot.weapon,
      statBonuses: {'strength': 800, 'willpower': 400, 'ninjutsu': 300},
      statMultipliers: {'strength': 1.4, 'ninjutsu': 1.2},
      specialEffects: ['thunder_call', 'lightning_storm', 'stun'],
      durability: 300,
      maxDurability: 300,
      isRepairable: true,
      isTradeable: false,
      isDroppable: false,
      buyPrice: 25000,
      sellPrice: 12500,
      shopCategory: 'weapons',
      isAvailableInShop: true,
      requiredLevel: 35,
      statRequirements: {'strength': 30000, 'willpower': 20000},
      requiredElements: ['lightning'],
      requiredBloodline: null,
      iconPath: 'assets/items/thunder_hammer.png',
      tags: ['weapon', 'hammer', 'legendary'],
      isActive: true,
      rarity: 'Legendary',
    ),

    // HEAD GEAR
    Item(
      id: 'item_7',
      name: 'Basic Headband',
      description: 'A simple cloth headband with your village symbol.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.head,
      statBonuses: {'willpower': 50},
      statMultipliers: {},
      specialEffects: ['village_pride'],
      durability: 50,
      maxDurability: 50,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 50,
      sellPrice: 25,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 1,
      statRequirements: {},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/basic_headband.png',
      tags: ['armor', 'head', 'basic'],
      isActive: true,
      rarity: 'Common',
    ),
    Item(
      id: 'item_8',
      name: 'Steel Helmet',
      description: 'A sturdy steel helmet that provides excellent head protection.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.head,
      statBonuses: {'defense': 200, 'willpower': 100},
      statMultipliers: {'defense': 1.1},
      specialEffects: ['head_protection', 'stun_resistance'],
      durability: 120,
      maxDurability: 120,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 800,
      sellPrice: 400,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 5,
      statRequirements: {'defense': 3000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/steel_helmet.png',
      tags: ['armor', 'head', 'steel'],
      isActive: true,
      rarity: 'Uncommon',
    ),
    Item(
      id: 'item_9',
      name: 'Chakra Sensing Headband',
      description: 'A special headband that enhances chakra sensing abilities.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.head,
      statBonuses: {'intelligence': 300, 'ninjutsu': 200, 'genjutsu': 150},
      statMultipliers: {'intelligence': 1.15},
      specialEffects: ['chakra_sensing', 'genjutsu_resistance', 'stealth_detection'],
      durability: 100,
      maxDurability: 100,
      isRepairable: true,
      isTradeable: true,
      isDroppable: false,
      buyPrice: 3000,
      sellPrice: 1500,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 12,
      statRequirements: {'intelligence': 8000, 'ninjutsu': 5000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/chakra_sensing_headband.png',
      tags: ['armor', 'head', 'sensory'],
      isActive: true,
      rarity: 'Rare',
    ),
    Item(
      id: 'item_10',
      name: 'Crown of the Sage',
      description: 'An ancient crown that grants wisdom and power beyond mortal ken.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.head,
      statBonuses: {'intelligence': 500, 'willpower': 400, 'ninjutsu': 300},
      statMultipliers: {'intelligence': 1.3, 'ninjutsu': 1.2},
      specialEffects: ['sage_wisdom', 'chakra_mastery', 'elemental_affinity'],
      durability: 200,
      maxDurability: 200,
      isRepairable: true,
      isTradeable: false,
      isDroppable: false,
      buyPrice: 20000,
      sellPrice: 10000,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 30,
      statRequirements: {'intelligence': 25000, 'willpower': 20000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/crown_of_sage.png',
      tags: ['armor', 'head', 'legendary'],
      isActive: true,
      rarity: 'Legendary',
    ),

    // ARM GEAR
    Item(
      id: 'item_11',
      name: 'Cloth Arm Wraps',
      description: 'Simple cloth wraps that protect your arms during training.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.arms,
      statBonuses: {'defense': 50, 'taijutsu': 30},
      statMultipliers: {},
      specialEffects: ['training_protection'],
      durability: 40,
      maxDurability: 40,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 75,
      sellPrice: 35,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 1,
      statRequirements: {},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/cloth_arm_wraps.png',
      tags: ['armor', 'arms', 'basic'],
      isActive: true,
      rarity: 'Common',
    ),
    Item(
      id: 'item_12',
      name: 'Leather Bracers',
      description: 'Tough leather bracers that provide good arm protection.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.arms,
      statBonuses: {'defense': 150, 'strength': 100, 'taijutsu': 80},
      statMultipliers: {'strength': 1.05},
      specialEffects: ['arm_protection', 'grappling_boost'],
      durability: 100,
      maxDurability: 100,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 400,
      sellPrice: 200,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 4,
      statRequirements: {'strength': 2000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/leather_bracers.png',
      tags: ['armor', 'arms', 'leather'],
      isActive: true,
      rarity: 'Uncommon',
    ),
    Item(
      id: 'item_13',
      name: 'Chakra Gauntlets',
      description: 'Gauntlets that channel chakra to enhance punching power.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.arms,
      statBonuses: {'strength': 300, 'taijutsu': 250, 'ninjutsu': 150},
      statMultipliers: {'strength': 1.15, 'taijutsu': 1.1},
      specialEffects: ['chakra_enhanced_strikes', 'elemental_punches'],
      durability: 150,
      maxDurability: 150,
      isRepairable: true,
      isTradeable: true,
      isDroppable: false,
      buyPrice: 2000,
      sellPrice: 1000,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 10,
      statRequirements: {'strength': 8000, 'ninjutsu': 4000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/chakra_gauntlets.png',
      tags: ['armor', 'arms', 'chakra'],
      isActive: true,
      rarity: 'Rare',
    ),
    Item(
      id: 'item_14',
      name: 'Dragon Scale Bracers',
      description: 'Bracers made from dragon scales. Extremely durable and powerful.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.arms,
      statBonuses: {'strength': 500, 'defense': 400, 'taijutsu': 400},
      statMultipliers: {'strength': 1.25, 'defense': 1.2},
      specialEffects: ['dragon_scales', 'fire_resistance', 'crushing_blows'],
      durability: 300,
      maxDurability: 300,
      isRepairable: true,
      isTradeable: false,
      isDroppable: false,
      buyPrice: 15000,
      sellPrice: 7500,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 25,
      statRequirements: {'strength': 20000, 'defense': 15000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/dragon_scale_bracers.png',
      tags: ['armor', 'arms', 'epic'],
      isActive: true,
      rarity: 'Epic',
    ),

    // BODY ARMOR
    Item(
      id: 'item_15',
      name: 'Basic Shinobi Vest',
      description: 'A standard vest worn by all ninja. Provides basic protection.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.body,
      statBonuses: {'defense': 100, 'willpower': 50},
      statMultipliers: {},
      specialEffects: ['basic_protection'],
      durability: 80,
      maxDurability: 80,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 200,
      sellPrice: 100,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 1,
      statRequirements: {},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/basic_shinobi_vest.png',
      tags: ['armor', 'body', 'basic'],
      isActive: true,
      rarity: 'Common',
    ),
    Item(
      id: 'item_16',
      name: 'Elite Shinobi Vest',
      description: 'High-quality armor worn by experienced ninja. Provides excellent protection.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.body,
      statBonuses: {'defense': 500, 'willpower': 200},
      statMultipliers: {'defense': 1.1},
      specialEffects: ['damage_reduction', 'chakra_resistance'],
      durability: 200,
      maxDurability: 200,
      isRepairable: true,
      isTradeable: true,
      isDroppable: false,
      buyPrice: 5000,
      sellPrice: 2500,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 15,
      statRequirements: {'defense': 8000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/shinobi_vest.png',
      tags: ['armor', 'body', 'elite'],
      isActive: true,
      rarity: 'Rare',
    ),
    Item(
      id: 'item_17',
      name: 'Chakra Weave Armor',
      description: 'Armor woven with chakra threads. Provides both protection and chakra enhancement.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.body,
      statBonuses: {'defense': 800, 'willpower': 400, 'ninjutsu': 300},
      statMultipliers: {'defense': 1.2, 'ninjutsu': 1.1},
      specialEffects: ['chakra_weave', 'elemental_resistance', 'chakra_boost'],
      durability: 250,
      maxDurability: 250,
      isRepairable: true,
      isTradeable: true,
      isDroppable: false,
      buyPrice: 12000,
      sellPrice: 6000,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 20,
      statRequirements: {'defense': 15000, 'ninjutsu': 10000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/chakra_weave_armor.png',
      tags: ['armor', 'body', 'chakra'],
      isActive: true,
      rarity: 'Epic',
    ),
    Item(
      id: 'item_18',
      name: 'Sage Robes',
      description: 'Mystical robes that grant the wearer sage-like abilities and wisdom.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.body,
      statBonuses: {'defense': 1000, 'willpower': 600, 'intelligence': 500},
      statMultipliers: {'defense': 1.3, 'willpower': 1.2, 'intelligence': 1.15},
      specialEffects: ['sage_wisdom', 'natural_chakra', 'elemental_mastery'],
      durability: 400,
      maxDurability: 400,
      isRepairable: true,
      isTradeable: false,
      isDroppable: false,
      buyPrice: 30000,
      sellPrice: 15000,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 35,
      statRequirements: {'defense': 25000, 'willpower': 20000, 'intelligence': 18000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/sage_robes.png',
      tags: ['armor', 'body', 'legendary'],
      isActive: true,
      rarity: 'Legendary',
    ),

    // LEG GEAR
    Item(
      id: 'item_19',
      name: 'Cloth Pants',
      description: 'Simple cloth pants that provide basic leg protection.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.legs,
      statBonuses: {'defense': 50, 'speed': 30},
      statMultipliers: {},
      specialEffects: ['basic_mobility'],
      durability: 60,
      maxDurability: 60,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 100,
      sellPrice: 50,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 1,
      statRequirements: {},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/cloth_pants.png',
      tags: ['armor', 'legs', 'basic'],
      isActive: true,
      rarity: 'Common',
    ),
    Item(
      id: 'item_20',
      name: 'Leather Leggings',
      description: 'Tough leather leggings that provide good leg protection.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.legs,
      statBonuses: {'defense': 150, 'speed': 100, 'taijutsu': 80},
      statMultipliers: {'speed': 1.05},
      specialEffects: ['leg_protection', 'kicking_boost'],
      durability: 120,
      maxDurability: 120,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 500,
      sellPrice: 250,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 5,
      statRequirements: {'speed': 3000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/leather_leggings.png',
      tags: ['armor', 'legs', 'leather'],
      isActive: true,
      rarity: 'Uncommon',
    ),
    Item(
      id: 'item_21',
      name: 'Wind Chakra Pants',
      description: 'Pants infused with wind chakra that enhance movement speed.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.legs,
      statBonuses: {'speed': 300, 'defense': 200, 'ninjutsu': 150},
      statMultipliers: {'speed': 1.2},
      specialEffects: ['wind_enhanced_movement', 'air_walking', 'speed_boost'],
      durability: 180,
      maxDurability: 180,
      isRepairable: true,
      isTradeable: true,
      isDroppable: false,
      buyPrice: 3000,
      sellPrice: 1500,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 12,
      statRequirements: {'speed': 10000, 'ninjutsu': 6000},
      requiredElements: ['wind'],
      requiredBloodline: null,
      iconPath: 'assets/items/wind_chakra_pants.png',
      tags: ['armor', 'legs', 'wind'],
      isActive: true,
      rarity: 'Rare',
    ),
    Item(
      id: 'item_22',
      name: 'Thunder Greaves',
      description: 'Greaves that channel lightning chakra for incredible speed.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.legs,
      statBonuses: {'speed': 500, 'defense': 300, 'strength': 200},
      statMultipliers: {'speed': 1.3, 'strength': 1.1},
      specialEffects: ['lightning_speed', 'thunder_stomp', 'chain_lightning'],
      durability: 250,
      maxDurability: 250,
      isRepairable: true,
      isTradeable: false,
      isDroppable: false,
      buyPrice: 18000,
      sellPrice: 9000,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 28,
      statRequirements: {'speed': 20000, 'strength': 12000},
      requiredElements: ['lightning'],
      requiredBloodline: null,
      iconPath: 'assets/items/thunder_greaves.png',
      tags: ['armor', 'legs', 'epic'],
      isActive: true,
      rarity: 'Epic',
    ),

    // FOOT GEAR
    Item(
      id: 'item_23',
      name: 'Basic Sandals',
      description: 'Simple wooden sandals worn by most ninja.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.feet,
      statBonuses: {'speed': 50},
      statMultipliers: {},
      specialEffects: ['basic_movement'],
      durability: 40,
      maxDurability: 40,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 50,
      sellPrice: 25,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 1,
      statRequirements: {},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/basic_sandals.png',
      tags: ['armor', 'feet', 'basic'],
      isActive: true,
      rarity: 'Common',
    ),
    Item(
      id: 'item_24',
      name: 'Leather Boots',
      description: 'Sturdy leather boots that provide good foot protection.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.feet,
      statBonuses: {'speed': 120, 'defense': 80},
      statMultipliers: {'speed': 1.05},
      specialEffects: ['foot_protection', 'silent_movement'],
      durability: 100,
      maxDurability: 100,
      isRepairable: true,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 300,
      sellPrice: 150,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 3,
      statRequirements: {'speed': 2000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/leather_boots.png',
      tags: ['armor', 'feet', 'leather'],
      isActive: true,
      rarity: 'Uncommon',
    ),
    Item(
      id: 'item_25',
      name: 'Ninja Tabi',
      description: 'Specialized ninja footwear that enhances stealth and movement.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.feet,
      statBonuses: {'speed': 200, 'defense': 100, 'taijutsu': 100},
      statMultipliers: {'speed': 1.1, 'taijutsu': 1.05},
      specialEffects: ['enhanced_stealth', 'wall_walking', 'silent_steps'],
      durability: 150,
      maxDurability: 150,
      isRepairable: true,
      isTradeable: true,
      isDroppable: false,
      buyPrice: 1500,
      sellPrice: 750,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 8,
      statRequirements: {'speed': 6000, 'taijutsu': 4000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/ninja_tabi.png',
      tags: ['armor', 'feet', 'stealth'],
      isActive: true,
      rarity: 'Rare',
    ),
    Item(
      id: 'item_26',
      name: 'Phoenix Wings',
      description: 'Boots that grant the wearer the ability to walk on air and flames.',
      type: ItemType.armor,
      equipmentSlot: EquipmentSlot.feet,
      statBonuses: {'speed': 400, 'defense': 200, 'ninjutsu': 200},
      statMultipliers: {'speed': 1.25, 'ninjutsu': 1.1},
      specialEffects: ['air_walking', 'fire_walking', 'phoenix_flight'],
      durability: 200,
      maxDurability: 200,
      isRepairable: true,
      isTradeable: false,
      isDroppable: false,
      buyPrice: 20000,
      sellPrice: 10000,
      shopCategory: 'armor',
      isAvailableInShop: true,
      requiredLevel: 30,
      statRequirements: {'speed': 25000, 'ninjutsu': 15000},
      requiredElements: ['fire'],
      requiredBloodline: null,
      iconPath: 'assets/items/phoenix_wings.png',
      tags: ['armor', 'feet', 'legendary'],
      isActive: true,
      rarity: 'Legendary',
    ),

    // CONSUMABLES
    Item(
      id: 'item_27',
      name: 'Chakra Potion',
      description: 'Restores chakra when consumed. Essential for long missions.',
      type: ItemType.consumable,
      equipmentSlot: null,
      statBonuses: {},
      statMultipliers: {},
      specialEffects: ['restore_chakra'],
      durability: null,
      maxDurability: null,
      isRepairable: false,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 200,
      sellPrice: 100,
      shopCategory: 'consumables',
      isAvailableInShop: true,
      requiredLevel: 1,
      statRequirements: {},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/chakra_potion.png',
      tags: ['consumable', 'chakra', 'healing'],
      isActive: true,
      rarity: 'Common',
    ),
    Item(
      id: 'item_28',
      name: 'Health Elixir',
      description: 'A powerful healing potion that restores significant health.',
      type: ItemType.consumable,
      equipmentSlot: null,
      statBonuses: {},
      statMultipliers: {},
      specialEffects: ['restore_health'],
      durability: null,
      maxDurability: null,
      isRepairable: false,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 500,
      sellPrice: 250,
      shopCategory: 'consumables',
      isAvailableInShop: true,
      requiredLevel: 1,
      statRequirements: {},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/health_elixir.png',
      tags: ['consumable', 'health', 'healing'],
      isActive: true,
      rarity: 'Uncommon',
    ),
    Item(
      id: 'item_29',
      name: 'Stamina Tonic',
      description: 'Restores stamina and provides a temporary speed boost.',
      type: ItemType.consumable,
      equipmentSlot: null,
      statBonuses: {},
      statMultipliers: {},
      specialEffects: ['restore_stamina', 'speed_boost'],
      durability: null,
      maxDurability: null,
      isRepairable: false,
      isTradeable: true,
      isDroppable: true,
      buyPrice: 300,
      sellPrice: 150,
      shopCategory: 'consumables',
      isAvailableInShop: true,
      requiredLevel: 1,
      statRequirements: {},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/stamina_tonic.png',
      tags: ['consumable', 'stamina', 'boost'],
      isActive: true,
      rarity: 'Uncommon',
    ),
    Item(
      id: 'item_30',
      name: 'Sage Elixir',
      description: 'A rare elixir that temporarily grants sage-like abilities.',
      type: ItemType.consumable,
      equipmentSlot: null,
      statBonuses: {},
      statMultipliers: {},
      specialEffects: ['sage_mode', 'chakra_boost', 'elemental_enhancement'],
      durability: null,
      maxDurability: null,
      isRepairable: false,
      isTradeable: true,
      isDroppable: false,
      buyPrice: 5000,
      sellPrice: 2500,
      shopCategory: 'consumables',
      isAvailableInShop: true,
      requiredLevel: 20,
      statRequirements: {'willpower': 10000},
      requiredElements: [],
      requiredBloodline: null,
      iconPath: 'assets/items/sage_elixir.png',
      tags: ['consumable', 'sage', 'temporary'],
      isActive: true,
      rarity: 'Epic',
    ),
  ];

  // World data
  World get sampleWorld => World(
    id: 'world_1',
    width: 25,
    height: 25,
    tiles: _generateWorldTiles(),
    villageLocations: _generateVillageLocations(),
    activePlayers: ['user_1', 'user_2'],
    lastUpdated: DateTime.now(),
  );

  // Helper methods
  List<WorldTile> _generateWorldTiles() {
    final tiles = <WorldTile>[];
    
    for (int y = 0; y < 25; y++) {
      for (int x = 0; x < 25; x++) {
        // Village tiles
        if ((x == 12 && y == 12) || // Konoha center
            (x == 2 && y == 2) ||   // Suna
            (x == 22 && y == 2) ||  // Kiri
            (x == 2 && y == 22) ||  // Iwa
            (x == 22 && y == 22)) { // Kumo
          tiles.add(WorldTile(
            x: x,
            y: y,
            type: TileType.village,
            villageType: _getVillageType(x, y),
            villageName: _getVillageName(x, y),
            description: 'A bustling ninja village',
            availableActions: ['move', 'rest', 'shop', 'train'],
            isOccupied: false,
            occupiedBy: null,
            statModifiers: {'defense': 1.2, 'willpower': 1.1},
            specialEffects: ['safe_zone', 'healing'],
            dangerLevel: 0,
            isRestricted: false,
          ));
        }
        // PvP zones
        else if ((x == 10 && y == 10) || (x == 14 && y == 14)) {
          tiles.add(WorldTile(
            x: x,
            y: y,
            type: TileType.pvp,
            villageType: null,
            villageName: null,
            description: 'Dangerous PvP zone',
            availableActions: ['move', 'fight', 'gather'],
            isOccupied: false,
            occupiedBy: null,
            statModifiers: {'speed': 1.1, 'strength': 1.1},
            specialEffects: ['pvp_enabled', 'increased_rewards'],
            dangerLevel: 8,
            isRestricted: false,
          ));
        }
        // PvE zones
        else if ((x == 5 && y == 5) || (x == 19 && y == 19)) {
          tiles.add(WorldTile(
            x: x,
            y: y,
            type: TileType.pve,
            villageType: null,
            villageName: null,
            description: 'Wilderness with monsters',
            availableActions: ['move', 'hunt', 'gather'],
            isOccupied: false,
            occupiedBy: null,
            statModifiers: {'experience': 1.2},
            specialEffects: ['monster_spawns', 'resource_rich'],
            dangerLevel: 5,
            isRestricted: false,
          ));
        }
        // Default wilderness
        else {
          tiles.add(WorldTile(
            x: x,
            y: y,
            type: TileType.wilderness,
            villageType: null,
            villageName: null,
            description: 'Peaceful wilderness area',
            availableActions: ['move', 'rest', 'gather'],
            isOccupied: false,
            occupiedBy: null,
            statModifiers: {},
            specialEffects: [],
            dangerLevel: 2,
            isRestricted: false,
          ));
        }
      }
    }
    
    return tiles;
  }

  Map<String, WorldTile> _generateVillageLocations() {
    final locations = <String, WorldTile>{};
    final tiles = _generateWorldTiles();
    
    locations['konoha'] = tiles.firstWhere((t) => t.x == 12 && t.y == 12);
    locations['suna'] = tiles.firstWhere((t) => t.x == 2 && t.y == 2);
    locations['kiri'] = tiles.firstWhere((t) => t.x == 22 && t.y == 2);
    locations['iwa'] = tiles.firstWhere((t) => t.x == 2 && t.y == 22);
    locations['kumo'] = tiles.firstWhere((t) => t.x == 22 && t.y == 22);
    
    return locations;
  }

  String _getVillageType(int x, int y) {
    if (x == 12 && y == 12) return 'konoha';
    if (x == 2 && y == 2) return 'suna';
    if (x == 22 && y == 2) return 'kiri';
    if (x == 2 && y == 22) return 'iwa';
    if (x == 22 && y == 22) return 'kumo';
    return 'unknown';
  }

  String _getVillageName(int x, int y) {
    if (x == 12 && y == 12) return 'Konohagakure';
    if (x == 2 && y == 2) return 'Sunagakure';
    if (x == 22 && y == 2) return 'Kirigakure';
    if (x == 2 && y == 22) return 'Iwagakure';
    if (x == 22 && y == 22) return 'Kumogakure';
    return 'Unknown Village';
  }

  // Chat messages
  List<ChatMessage> get sampleChatMessages => [
    ChatMessage(
      id: 'msg_1',
      senderId: 'user_1',
      senderName: 'Naruto Uzumaki',
      senderAvatar: 'assets/avatars/naruto.png',
      chatType: ChatType.world,
      messageType: MessageType.text,
      content: 'Hey everyone! Just completed my first C-rank mission! 🎉',
      timestamp: DateTime.now().subtract(const Duration(minutes: 5)),
      editedAt: null,
      isEdited: false,
      isDeleted: false,
      targetId: null,
      villageName: null,
      clanName: null,
      recipientId: null,
      mentions: [],
      attachments: [],
      metadata: {},
      isModerated: false,
      moderationReason: null,
      isPinned: false,
      reactions: {'👍': ['user_2'], '🎉': ['user_3']},
      reactionCount: 2,
    ),
    ChatMessage(
      id: 'msg_2',
      senderId: 'user_2',
      senderName: 'Sasuke Uchiha',
      senderAvatar: 'assets/avatars/sasuke.png',
      chatType: ChatType.village,
      messageType: MessageType.text,
      content: 'Anyone up for some training at the arena?',
      timestamp: DateTime.now().subtract(const Duration(minutes: 3)),
      editedAt: null,
      isEdited: false,
      isDeleted: false,
      targetId: 'konoha',
      villageName: 'Konoha',
      clanName: null,
      recipientId: null,
      mentions: [],
      attachments: [],
      metadata: {},
      isModerated: false,
      moderationReason: null,
      isPinned: false,
      reactions: {'⚔️': ['user_1']},
      reactionCount: 1,
    ),
  ];

  // User data
  List<User> get sampleUsers => [
    User(
      id: 'user_1',
      username: 'naruto_uzumaki',
      email: 'naruto@konoha.com',
      createdAt: DateTime(2020, 1, 1),
      lastLogin: DateTime.now(),
      isActive: true,
      isVerified: true,
      displayName: 'Naruto Uzumaki',
      avatarUrl: 'assets/avatars/naruto.png',
      bio: 'Believe it! Future Hokage!',
      preferences: {'theme': 'dark', 'notifications': true},
      isBanned: false,
      banReason: null,
      banExpiry: null,
      warningCount: 0,
      friends: ['user_2', 'user_3'],
      blockedUsers: [],
      ignoredUsers: [],
      currentCharacterId: 'char_1',
      characterIds: ['char_1'],
      lastVillage: 'Konoha',
      lastActivity: DateTime.now(),
    ),
    User(
      id: 'user_2',
      username: 'sasuke_uchiha',
      email: 'sasuke@konoha.com',
      createdAt: DateTime(2020, 1, 1),
      lastLogin: DateTime.now().subtract(const Duration(hours: 1)),
      isActive: true,
      isVerified: true,
      displayName: 'Sasuke Uchiha',
      avatarUrl: 'assets/avatars/sasuke.png',
      bio: 'Seeking power to restore my clan.',
      preferences: {'theme': 'dark', 'notifications': false},
      isBanned: false,
      banReason: null,
      banExpiry: null,
      warningCount: 1,
      friends: ['user_1'],
      blockedUsers: [],
      ignoredUsers: [],
      currentCharacterId: 'char_2',
      characterIds: ['char_2'],
      lastVillage: 'Konoha',
      lastActivity: DateTime.now().subtract(const Duration(hours: 1)),
    ),
  ];
}
