// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASTb9FmSTadDNzBVPwO5y8OvitiuJmxao',
    appId: '1:781685618847:web:7be97574bfd0b8137e4aaa',
    messagingSenderId: '781685618847',
    projectId: 'ninja-world-mmo',
    authDomain: 'ninja-world-mmo.firebaseapp.com',
    databaseURL: 'https://ninja-world-mmo-default-rtdb.firebaseio.com',
    storageBucket: 'ninja-world-mmo.firebasestorage.app',
    measurementId: 'G-7E1DY5NSPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZTrVrqMfIsnOb3zAL22Fx0OQJDHueLGQ',
    appId: '1:781685618847:android:91d0dfaa1123c7ab7e4aaa',
    messagingSenderId: '781685618847',
    projectId: 'ninja-world-mmo',
    databaseURL: 'https://ninja-world-mmo-default-rtdb.firebaseio.com',
    storageBucket: 'ninja-world-mmo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACF57UDh4lCIwdrTskwRTUQW_q8qtrziw',
    appId: '1:781685618847:ios:0b4b07029c9ae8097e4aaa',
    messagingSenderId: '781685618847',
    projectId: 'ninja-world-mmo',
    databaseURL: 'https://ninja-world-mmo-default-rtdb.firebaseio.com',
    storageBucket: 'ninja-world-mmo.firebasestorage.app',
    iosBundleId: 'com.ninjaworld.ninjaWorldMmo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACF57UDh4lCIwdrTskwRTUQW_q8qtrziw',
    appId: '1:781685618847:ios:0b4b07029c9ae8097e4aaa',
    messagingSenderId: '781685618847',
    projectId: 'ninja-world-mmo',
    databaseURL: 'https://ninja-world-mmo-default-rtdb.firebaseio.com',
    storageBucket: 'ninja-world-mmo.firebasestorage.app',
    iosBundleId: 'com.ninjaworld.ninjaWorldMmo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASTb9FmSTadDNzBVPwO5y8OvitiuJmxao',
    appId: '1:781685618847:web:2a56ca1a4491a6187e4aaa',
    messagingSenderId: '781685618847',
    projectId: 'ninja-world-mmo',
    databaseURL: 'https://ninja-world-mmo-default-rtdb.firebaseio.com',
    storageBucket: 'ninja-world-mmo.firebasestorage.app',
    measurementId: 'G-JRBLQ5MTT4',
  );
}
